-- Additive J2 schema migration
-- Non-destructive: creates missing tables and indexes only.
-- Safe to run on an existing database because it never drops or alters existing tables.

CREATE TABLE IF NOT EXISTS "Division" (
    division_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_name VARCHAR,
    district VARCHAR,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    province VARCHAR,
    division_population INTEGER
);

CREATE TABLE IF NOT EXISTS "IoT_Device" (
    device_id VARCHAR PRIMARY KEY,
    division_id INTEGER REFERENCES "Division"(division_id),
    installation_date DATE,
    status VARCHAR
);

CREATE TABLE IF NOT EXISTS "iot_rainfall_data" (
    row_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    temp DOUBLE PRECISION,
    hum DOUBLE PRECISION,
    depth DOUBLE PRECISION,
    recorded_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS raw_telemetry (
    telemetry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR NOT NULL,
    division_id INTEGER REFERENCES "Division"(division_id),
    hazard_type VARCHAR NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    temp DOUBLE PRECISION,
    hum DOUBLE PRECISION,
    depth DOUBLE PRECISION,
    moist DOUBLE PRECISION,
    ax DOUBLE PRECISION,
    ay DOUBLE PRECISION,
    az DOUBLE PRECISION,
    gx DOUBLE PRECISION,
    gy DOUBLE PRECISION,
    gz DOUBLE PRECISION,
    raw_payload TEXT,
    recorded_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS computed_features (
    feature_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id INTEGER NOT NULL REFERENCES "Division"(division_id),
    date DATE NOT NULL,
    rain_lag_1 DOUBLE PRECISION,
    rain_rolling_3d DOUBLE PRECISION,
    rain_rolling_7d DOUBLE PRECISION,
    month_sin DOUBLE PRECISION,
    month_cos DOUBLE PRECISION,
    spi DOUBLE PRECISION,
    division_encoded INTEGER,
    level_difference DOUBLE PRECISION,
    CONSTRAINT idx_computed_features_div_date UNIQUE (division_id, date)
);

CREATE TABLE IF NOT EXISTS "Division_Resources" (
    division_id INTEGER PRIMARY KEY REFERENCES "Division"(division_id),
    created_at TIMESTAMPTZ,
    hospital_bed_capacity INTEGER,
    emergency_shelters INTEGER,
    ambulance_count INTEGER,
    food_stock_tons DOUBLE PRECISION,
    clean_water_capacity_liters DOUBLE PRECISION,
    power_grid_resilience DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS disaster_predictions (
    prediction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id INTEGER NOT NULL REFERENCES "Division"(division_id),
    feature_date DATE NOT NULL,
    predicted_for_date DATE NOT NULL,
    horizon INTEGER NOT NULL,
    hazard_type VARCHAR NOT NULL,
    prob_normal DOUBLE PRECISION,
    prob_moderate DOUBLE PRECISION,
    prob_severe DOUBLE PRECISION,
    prob_extreme DOUBLE PRECISION,
    predicted_severity INTEGER,
    predicted_severity_label VARCHAR,
    run_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS resource_recommendations (
    recommendation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id INTEGER NOT NULL REFERENCES "Division"(division_id),
    hazard_type VARCHAR NOT NULL,
    risk_category VARCHAR NOT NULL,
    consideration_score DOUBLE PRECISION,
    recommendation_text TEXT,
    resource_allocation_json TEXT,
    model_name VARCHAR,
    created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "Resource" (
    id VARCHAR PRIMARY KEY,
    type VARCHAR,
    name VARCHAR,
    district VARCHAR,
    status VARCHAR,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    capacity INTEGER,
    "currentLoad" INTEGER,
    "lastUpdated" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "RainfallData" (
    rainfall_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id INTEGER NOT NULL REFERENCES "Division"(division_id),
    date DATE NOT NULL,
    rain_sum DOUBLE PRECISION,
    CONSTRAINT idx_rainfall_div_date UNIQUE (division_id, date)
);

CREATE TABLE IF NOT EXISTS "SoilMoisture" (
    soil_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id INTEGER NOT NULL REFERENCES "Division"(division_id),
    date DATE NOT NULL,
    moisture_7_28cm DOUBLE PRECISION,
    moisture_28_100cm DOUBLE PRECISION,
    moisture_100_255cm DOUBLE PRECISION,
    CONSTRAINT idx_soil_div_date UNIQUE (division_id, date)
);

CREATE TABLE IF NOT EXISTS "TemperatureData" (
    temp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id INTEGER NOT NULL REFERENCES "Division"(division_id),
    date DATE NOT NULL,
    temperature DOUBLE PRECISION,
    CONSTRAINT idx_temp_div_date UNIQUE (division_id, date)
);

CREATE TABLE IF NOT EXISTS "Predictions" (
    prediction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id INTEGER NOT NULL REFERENCES "Division"(division_id),
    date DATE NOT NULL,
    flood_probability DOUBLE PRECISION,
    landslide_probability DOUBLE PRECISION,
    drought_probability DOUBLE PRECISION,
    consideration_score DOUBLE PRECISION,
    CONSTRAINT idx_pred_div_date UNIQUE (division_id, date)
);

CREATE INDEX IF NOT EXISTS idx_raw_telemetry_division_id ON raw_telemetry (division_id);
CREATE INDEX IF NOT EXISTS idx_raw_telemetry_device_id ON raw_telemetry (device_id);
CREATE INDEX IF NOT EXISTS idx_raw_telemetry_hazard_type ON raw_telemetry (hazard_type);
CREATE INDEX IF NOT EXISTS idx_disaster_predictions_division_id ON disaster_predictions (division_id);
CREATE INDEX IF NOT EXISTS idx_disaster_predictions_run_at ON disaster_predictions (run_at);
CREATE INDEX IF NOT EXISTS idx_resource_recommendations_division_id ON resource_recommendations (division_id);
CREATE INDEX IF NOT EXISTS idx_resource_recommendations_created_at ON resource_recommendations (created_at);
