stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: disasterdb
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: changeme
  KONG_DB_USER: kong
  KONG_DB_PASSWORD: changeme
  KONG_DB_NAME: kong
  GF_SECURITY_ADMIN_PASSWORD: changeme
  DATABASE_URL: "postgresql://j3user:CHANGEME@postgres:5432/j3db"
  AUDIT_PRIVATE_KEY: "0xYOUR_HARDHAT_PRIVATE_KEY_HERE"