from app.models.base_water_level import BaseWaterLevel
from app.models.disaster_risk import DisasterRisk
from app.models.division import Division
from app.models.flood_severity import FloodSeverity
from app.models.iot_device import IoTDevice
from app.models.rainfall_data import RainfallData
from app.models.soil_moisture import SoilMoisture
from app.models.spi_data import SPIData
from app.models.temperature_data import TemperatureData