#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${J3_DB_USER} WITH PASSWORD '${J3_DB_PASSWORD}';
  CREATE DATABASE ${J3_DB_NAME} OWNER ${J3_DB_USER};

  CREATE USER ${KONG_DB_USER} WITH PASSWORD '${KONG_DB_PASSWORD}';
  CREATE DATABASE ${KONG_DB_NAME} OWNER ${KONG_DB_USER};

  CREATE USER ${KC_DB_USERNAME} WITH PASSWORD '${KC_DB_PASSWORD}';
  CREATE DATABASE keycloak OWNER ${KC_DB_USERNAME};
EOSQL
